function loadSounds()

% taken from presentation/aud_p3-1.70.sce
snd_fname.std    ='stimuli/1000HZ_150ms.wav'                 
snd_fname.tgt    ='stimuli/2000HZ_150ms.wav'                 
snd_fname.novel1 ='stimuli/ZCROW_new150.wav'                 
snd_fname.novel2 ='stimuli/ZNOSE_new150.wav'                 
snd_fname.novel3 ='stimuli/ZWHIP_new150.wav'                 
snd_fname.novel4 ='stimuli/ZWHALE_new150.wav'                
snd_fname.novel5 ='stimuli/ZPINBALL_new150.wav'              
snd_fname.novel6 ='stimuli/ZKNOCK_new150.wav'                
snd_fname.novel7 ='stimuli/ZHICCUP_new150.wav'               
snd_fname.novel8 ='stimuli/ZHERON_new150.wav'                
snd_fname.novel8 ='stimuli/ZHERON_new150_variant.wav'        
snd_fname.novel9 ='stimuli/ZMOSQUI_new150.wav'               
snd_fname.novel10='stimuli/ZHEART_new150.wav'                
snd_fname.novel11='stimuli/ZTOILET_new150.wav'               
snd_fname.novel12='stimuli/ZTRAIN_new150.wav'                
snd_fname.novel13='stimuli/ZWHISTLE_new150.wav'              
snd_fname.novel14='stimuli/ZTHROAT1_new150.wav'              
snd_fname.novel15='stimuli/ZCRICKET_new150.wav'              
snd_fname.novel16='stimuli/ZRACE_new150.wav'                 
snd_fname.novel17='stimuli/ZTURKEY_new150.wav'               
snd_fname.novel18='stimuli/ZCUCKOO_new150.wav'               
snd_fname.novel19='stimuli/ZDENTIST_new150.wav'              
snd_fname.novel20='stimuli/ZRAVEN_new150.wav'                
snd_fname.novel21='stimuli/ZGOOSE_new150.wav'                
snd_fname.novel22='stimuli/ZGUN_new150.wav'                  
snd_fname.novel23='stimuli/ZPIG1_new150.wav'                 
snd_fname.novel24='stimuli/ZRATTLE_new150.wav'               
snd_fname.novel25='stimuli/ZHOLLOW_new150.wav'               
snd_fname.novel26='stimuli/ZHORSE1_new150.wav'               
snd_fname.novel27='stimuli/ZHELICO_new150.wav'               
snd_fname.novel28='stimuli/ZHAMMER_new150.wav'               
snd_fname.novel29='stimuli/ZSNORE_new150.wav'                
snd_fname.novel29='stimuli/ZHERON_new150_variant.wav'        
snd_fname.novel30='stimuli/ZGADGET_new150.wav'               

sndlist = {
  'std', ...
  'tgt', ...
  'std', 'std', 'std', 'std', 'std', ...
  'tgt', ...
  'std', 'std', ...
  'tgt', ...
  'std', 'std', ...
  'tgt', ...
  'std', ...
  'tgt', ...
  'std', 'std', 'std', 'std', 'std', 'std', 'std', ...
  'novel1', ...
  'std', 'std', 'std', 'std', 'std', ...
  'novel2', ...
  'std', 'std', 'std', ...
  'novel3', ...
  'std', 'std', 'std', ...
  'novel4', ...
  'std', 'std', 'std', 'std', ...
  'novel5', ...
  'std', 'std', 'std', 'std', ...
  'novel6', ...
  'std', ...
  'novel7', ...
  'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', ...
  'tgt', 'tgt', 'tgt', ...
  'std', ...
  'novel8', 'novel9', ...
  'std', ...
  'tgt', ...
  'std', 'std', ...
  'tgt', ...
  'novel10', ...
  'std', 'std', 'std', 'std', ...
  'tgt', ...
  'std', ...
  'novel11', ...
  'std', 'std', 'std', ...
  'tgt', ...
  'std', 'std', 'std', 'std', 'std', ...
  'tgt', 'tgt', ...
  'novel12', ...
  'std', 'std', 'std', 'std', 'std', ...
  'novel13', 'novel14', ...
  'tgt', ...
  'std', 'std', ...
  'novel15', ...
  'std', ...
  'tgt', 'tgt', ...
  'std', 'std', ...
  'novel16', ...
  'std', ...
  'tgt', ...
  'std', 'std', ...
  'novel17', ...
  'std', 'std', ...
  'novel18', ...
  'std', ...
  'tgt', ...
  'std', 'std', 'std', ...
  'tgt', ...
  'std', ...
  'novel19', ...
  'tgt', ...
  'std', 'std', 'std', 'std', 'std', ...
  'novel20', ...
  'tgt', ...
  'std', 'std', 'std', 'std', 'std', 'std', ...
  'tgt', ...
  'novel21', 'novel22', ...
  'std', ...
  'tgt', ...
  'novel23', ...
  'std', 'std', 'std', 'std', 'std', ...
  'tgt', ...
  'std', ...
  'tgt', ...
  'std', 'std', ...
  'tgt', ...
  'novel24', ...
  'tgt', ...
  'std', 'std', ...
  'tgt', ...
  'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', ...
  'novel25', 'novel26', ...
  'std', ...
  'novel27', ...
  'std', 'std', 'std', 'std', ...
  'novel28', ...
  'std', ...
  'novel29', ...
  'std', ...
  'tgt', ...
  'std', ...
  'novel30', ...
  'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', 'std', ...
}



