function trial_info=runTrial(sndname,snd,keys,start,finish)
 % schedual the sound, wait until thisIdealStart time
 thisActualStart = playsnd( snd, start);

 % record response
 [resp, keyonset] = waitForKey(keys,finish);
 
 % score response
 isstd=strncmp('std',sndname,3);
 isCorrect = (resp==1 && isstd) || (resp==2 && ~isstd);

 % trial information as a struct
 trial_info = struct( ...
    'response', resp, ...
    'correct', isCorrect, ...
    'keyontime',  keyonset, ...
    'sndname',  sndname, ...
    'onset', thisActualStart, ...
    'rt', keyonset-thisActualStart,...
    'idealonset', start);
end
